version: "3.9"
services:
  mongodb:
    image: mongodb/mongodb-community-server:latest
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./mongodb_data:/data/db
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=admin
      - MONGODB_INITDB_ROOT_PASSWORD=admin
  
  qdrant:
    container_name: qdrant
    image: qdrant/qdrant:v1.9.2
    volumes:
      - ./qdrant-data:/qdrant/storage:z
    ports:
      - "6333:6333"
      - "6334:6334"
    networks:
      - network

networks:
  network:
    driver: bridge
